### ISSUE TITLE
REPORTE DE PRACTICA 5 PROCESO DE MODELO DE NEGOCIO

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-dinamita#1]
[REPORTE DE PRACTICA 5 PROCESO DE NEGOCIO.pdf](https://github.com/user-attachments/files/17251190/REPORTE.DE.PRACTICA.5.PROCESO.DE.NEGOCIO.pdf)

EQUIPO:
Diego Cruz Cruz
Marco Uriel Rosas Garcia
Irvin Jimenez Sanchez

**Comment by Kevinosorio77** [comment]
Trabajo realizado cumple con los estándares de la rubrica  20%

**Comment by josealfredo79** [comment]
No es un proceso de Negocio, se debe hacer con el Proceso, favor de evaluar, @Kevinosorio77 favor de evaluar lo que es...y @irvinjs22620075 realizar nuevamente la practica y favor de revisar el lider del proyecto antes de subir

**Comment by Kevinosorio77** [comment]
Retomando la indicación del ING retomando y siendo revisado por el lider y yo concluyo que cumple de nuevo con la rubrica pasa a tener el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
